version: '3'
services:
    frontend:
        build: ./front-end
        ports:
          - "443:443"
        depends_on:
          - mongo
        privileged: true
    
    mongo:
        build: ./mongo-docker
        networks:
            default:
                aliases:
                  - mongo
        volumes:
          - data:$MONGO_DATADIR

 


volumes:
    data:
